export const data = [
  {
    label: "UserId",
    placeholder: "Enter your email address",
    type: "email",
    name: "email",
    required: true,
    value: "",
    errorMsg: "",
  },
  {
    label: "Password",
    placeholder: "Enter your password",
    type: "password",
    name: "password",
    required: true,
    value: "",
    errorMsg: "",
  },
  {
    label: "Gender",
    type: "radio",
    name: "gender",
    options: ["Male", "Female", "Other"],
    value: "",
    errorMsg: "",
  },
  {
    label: "Hobbies",
    type: "checkbox",
    name: "hobbies",
    options: ["Circket", "Hockey", "Batminton", "Chess"],
    value: "",
    errorMsg: "",
  },
  {
    label: "Country",
    tag: "select",
    name: "country",
    options: ["India", "Canada", "England", "France", "US"],
    value: "",
    errorMsg: "",
  },
  {
    label: "Address",
    name: "address",
    placeholder: "Enter your address",
    value: "",
    errorMsg: "",
  },
  {
    label: "Image",
    name: "image",
    type: "file",
    value: "",
    errorMsg: "",
    imageName: "",
  },
];
